### PR TITLE
Change chat log to web chat

### PR DESCRIPTION
**Pull request by liushuyu**
This change is [Reviewable](https://reviewable.io/reviews/aosc-dev/website-content/2)

### CODE REVIEW

**Comment by liushuyu** [comment]
Oops, I think we should use `https`

**Comment by MingcongBai** [comment]
@liushuyu Of course.

**Comment by liushuyu** [comment]
Okay, so is it good to merge?

**Comment by MingcongBai** [comment]
@liushuyu LGTM.

**Pull request merged**
